### ISSUE TITLE
failed to build with poppler-0.32.0

### ISSUE THREAD

**Issue by microcai** [coolwanglu/pdf2htmlEX#511]
pdf2htmlEX-0.12/src/BackgroundRenderer/SplashBackgroundRenderer.cc:35:23: error: no matching function for call to ‘SplashOutputDev::SplashOutputDev(SplashColorMode, int, bool, SplashColorPtr, bool, bool)’

/usr/include/poppler/SplashOutputDev.h:171:3: note: candidate: SplashOutputDev::SplashOutputDev(SplashColorMode, int, GBool, SplashColorPtr, GBool, SplashThinLineMode, GBool)
/usr/include/poppler/SplashOutputDev.h:171:3: note:   no known conversion for argument 6 from ‘bool’ to ‘SplashThinLineMode’

**Comment by microcai** [comment]
```patch
From 15436399bc8ad127dae6e7bb1597202420f084d6 Mon Sep 17 00:00:00 2001
From: microcai <microcaicai@gmail.com>
Date: Sun, 26 Apr 2015 05:29:40 +0800
Subject: [PATCH] ab

---
 src/BackgroundRenderer/SplashBackgroundRenderer.cc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/BackgroundRenderer/SplashBackgroundRenderer.cc b/src/BackgroundRenderer/SplashBackgroundRenderer.cc
index 7a9f79b..06072a9 100644
--- a/src/BackgroundRenderer/SplashBackgroundRenderer.cc
+++ b/src/BackgroundRenderer/SplashBackgroundRenderer.cc
@@ -29,7 +29,7 @@ using std::unique_ptr;
 const SplashColor SplashBackgroundRenderer::white = {255,255,255};
 
 SplashBackgroundRenderer::SplashBackgroundRenderer(const string & imgFormat, HTMLRenderer * html_renderer, const Param & param)
-    : SplashOutputDev(splashModeRGB8, 4, gFalse, (SplashColorPtr)(&white), gTrue, gTrue)
+    : SplashOutputDev(splashModeRGB8, 4, gFalse, (SplashColorPtr)(&white), gTrue, splashThinLineDefault, gTrue)
     , html_renderer(html_renderer)
     , param(param)
     , format(imgFormat)
-- 
2.3.6
```

**Comment by coolwanglu** [comment]
Fixed. Thanks!
