### ISSUE TITLE
Problem Compiling

### ISSUE THREAD

**Issue by Kamek** [coolwanglu/pdf2htmlEX#18]
Trying to compile with gcc-4.7 on OSX Lion 10.7.4 with fontforge stable 20120731 from homebrew this is my compiler output :

``` ruby
/usr/local/Cellar/pdf2htmlEX/build master ✗ ➤ export CC=/usr/local/bin/gcc-4.7; export CXX=/usr/local/bin/g++-4.7; make   
[  7%] Building C object CMakeFiles/pdf2htmlEX.dir/src/ff.c.o
In file included from /usr/local/include/fontforge/fontforge.h:35,
                 from /usr/local/Cellar/pdf2htmlEX/src/ff.c:16:
/usr/local/include/fontforge/splinefont.h:1044:31: error: spiroentrypoints.h: No such file or directory
In file included from /usr/local/include/fontforge/fontforge.h:35,
                 from /usr/local/Cellar/pdf2htmlEX/src/ff.c:16:
/usr/local/include/fontforge/splinefont.h:1070: error: expected specifier-qualifier-list before ‘spiro_cp’
/usr/local/include/fontforge/splinefont.h:3201: error: expected ‘)’ before ‘*’ token
/usr/local/include/fontforge/splinefont.h:3202: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
/usr/local/include/fontforge/splinefont.h:3203: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
In file included from /usr/local/Cellar/pdf2htmlEX/src/ff.c:17:
/usr/local/include/fontforge/baseviews.h:67: error: expected specifier-qualifier-list before ‘spiro_cp’
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/src/ff.c.o] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [all] Error 2
/usr/local/Cellar/pdf2htmlEX/build master ✗ ➤ ls /usr/local/include/fontforge G spline
splinefont.h
```

**Comment by mikefaille** [comment]
In Fedora, I must install 
libspiro-devel
to fix : 
```  error: spiroentrypoints.h: No such file ```
