### ISSUE TITLE
poppler-config.h build issue

### ISSUE THREAD

**Issue by aborzanovic** [coolwanglu/pdf2htmlEX#457]
trying to compile on ubuntu 14.04
 cmake . runs fine, but make prints an error:

[  2%] Building CXX object CMakeFiles/pdf2htmlEX.dir/3rdparty/poppler/git/CairoFontEngine.cc.o
/home/ubuntu/workspace/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:36:28: fatal error: poppler-config.h: No such file or directory
 #include <poppler-config.h>
                            ^
compilation terminated.
make[2]: **\* [CMakeFiles/pdf2htmlEX.dir/3rdparty/poppler/git/CairoFontEngine.cc.o] Error 1
make[1]: **\* [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: **\* [all] Error 2

i have installed poppler(using "./configure --enable-xpdf-headers") and cairo (correctly, i presume)
thaks in advance
