### ISSUE TITLE
Unable to Compile in Ubuntu 12.04

### ISSUE THREAD

**Issue by seebrown** [coolwanglu/pdf2htmlEX#331]
Have been unsuccessful in compiling in Ubuntu 12.04, Here are the details

poppler 0.24.5 with --enable-xpdf-headers enabled
fontforge (20140101) fork by coolwanglu 

During PDF2HTMLEX make

First errors (FIXED):

```
  /usr/local/include/fontforge/fontforge.h:39:20: fatal error: xalloc.h: No such file or directory  FIXED by manually copying xalloc.h to requested folder
```

```
/usr/local/include/fontforge/fontforge.h:40:24: fatal error: xvasprintf.h: No such file or directory  FIXED by manually copying xvasprintf.h to requested folder
```

Final error (UNRESOLVED):

```
/pdf2htmlEX/src/util/ffw.c:102:12: error: ‘library_version_configuration’ undeclared (first use in this function)
```

Not too sure where to go from here?

Here is the full error message

```
In file included from /usr/local/include/fontforge/fontforge.h:30:0,
                 from /home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:16:
/usr/local/include/fontforge/fontforge-config.h:11:0: warning: "strdup" redefined [enabled by default]
/usr/include/x86_64-linux-gnu/bits/string2.h:1316:0: note: this is the location of the previous definition
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_finalize’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:86:9: warning: passing argument 1 of ‘GC_free’ discards ‘const’ qualifier from pointer target type [enabled by default]
/usr/local/include/gc/gc.h:436:21: note: expected ‘void *’ but argument is of type ‘const char *’
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:92:17: warning: passing argument 1 of ‘GC_free’ discards ‘const’ qualifier from pointer target type [enabled by default]
/usr/local/include/gc/gc.h:436:21: note: expected ‘void *’ but argument is of type ‘const char *’
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_get_version’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:102:12: error: ‘library_version_configuration’ undeclared (first use in this function)
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:102:12: note: each undeclared identifier is reported only once for each function it appears in
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_prepare_font’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:155:17: warning: implicit declaration of function ‘AltUniFree’ [-Wimplicit-function-declaration]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_do_reencode’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:192:9: warning: implicit declaration of function ‘EncMapFree’ [-Wimplicit-function-declaration]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:204:5: warning: implicit declaration of function ‘fontforge_calloc’ [-Wimplicit-function-declaration]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:204:22: warning: assignment makes pointer from integer without a cast [enabled by default]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_reencode_raw’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:228:22: warning: initialization makes pointer from integer without a cast [enabled by default]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_reencode_raw2’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:252:22: warning: initialization makes pointer from integer without a cast [enabled by default]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:256:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:256:18: warning: assignment from incompatible pointer type [enabled by default]
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c: In function ‘ffw_get_version’:
/home/moappi/lib/pdf2htmlEX2/pdf2htmlEX/src/util/ffw.c:103:1: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ankit217** [comment]
[ 54%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/math.cc.obj
[ 56%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/misc.cc.obj
[ 59%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/path.cc.obj
[ 62%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/unicode.cc.obj
[ 64%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/mingw.cc.obj
[ 67%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/ArgParser.cc.obj
[ 70%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Base64Stream.cc.obj
[ 72%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Color.cc.obj
[ 75%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/CoveredTextDetector.cc.obj
[ 78%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/DrawingTracer.cc.obj
[ 81%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLTextLine.cc.obj
[ 83%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLTextPage.cc.obj
[ 86%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Preprocessor.cc.obj
[ 89%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/StringFormatter.cc.obj
[ 91%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/TmpFiles.cc.obj
[ 94%] Linking CXX executable pdf2htmlEX.exe
CMakeFiles/pdf2htmlEX.dir/objects.a(ffw.c.obj):ffw.c:(.text+0xafa): undefined reference to `__printf__'
CMakeFiles/pdf2htmlEX.dir/objects.a(ffw.c.obj):ffw.c:(.text+0x77a): undefined reference to `libintl_fprintf'
CMakeFiles/pdf2htmlEX.dir/objects.a(ffw.c.obj):ffw.c:(.text.unlikely+0x33): undefined reference to `libintl_vfprintf'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/build.make:991: pdf2htmlEX.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:356: CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
